# Generated by Django 6.0.7 on 2026-09-08 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Test nomi')),
                ('grade_level', models.IntegerField(default=9, verbose_name='Sinf darajasi')),
                ('time_limit_minutes', models.IntegerField(default=15, verbose_name='Vaqt chegari (daqiqa)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Fan kodi')),
                ('icon', models.CharField(default='📚', max_length=50, verbose_name='Icon/Emoji')),
                ('color', models.CharField(default='#3B82F6', max_length=20, verbose_name='Rang (HEX)')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='GradeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Sinf nomi')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_classes', to=settings.AUTH_USER_MODEL, verbose_name='Sinf rahbari')),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Sinflar',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('option_a', models.CharField(max_length=255, verbose_name='A variant')),
                ('option_b', models.CharField(max_length=255, verbose_name='B variant')),
                ('option_c', models.CharField(max_length=255, verbose_name='C variant')),
                ('option_d', models.CharField(max_length=255, verbose_name='D variant')),
                ('correct_option', models.CharField(choices=[('A', 'A Variant'), ('B', 'B Variant'), ('C', 'C Variant'), ('D', 'D Variant')], max_length=1, verbose_name="To'g'ri javob")),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='apps.quiz', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Ota-onasining telefoni')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID')),
                ('grade_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='apps.gradeclass', verbose_name='Sinf')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name="To'g'ri javoblar soni")),
                ('total_questions', models.IntegerField(verbose_name='Jami savollar soni')),
                ('percentage', models.FloatField(verbose_name='Foiz (%)')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='apps.quiz', verbose_name='Test')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='apps.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Test Natijasi',
                'verbose_name_plural': 'Test Natijalari',
                'ordering': ['-percentage', '-completed_at'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='apps.subject', verbose_name='Fan'),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name="Vazifa topshirig'i")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(verbose_name='Topshirish muddati')),
                ('grade_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='apps.gradeclass', verbose_name='Sinf')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Uyga vazifa',
                'verbose_name_plural': 'Uyga vazifalar',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Baho (1-5 yoki 1-100)')),
                ('grade_type', models.CharField(choices=[('KUNDALIK', 'Kundalik dars'), ('NAZORAT', 'Nazorat ishi'), ('CHORAK', 'Choraklik baho'), ('HOMEWORK', 'Uyga vazifa')], default='KUNDALIK', max_length=20, verbose_name='Baho turi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='apps.student', verbose_name="O'quvchi")),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='apps.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Baho',
                'verbose_name_plural': 'Baholar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='apps.subject', verbose_name='Bosh fani')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba')], verbose_name='Hafta kuni')),
                ('time_slot', models.CharField(max_length=50, verbose_name='Vaqti (masalan, 08:30 - 09:15)')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Xona')),
                ('grade_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='apps.gradeclass', verbose_name='Sinf')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Dars Jadvali',
                'verbose_name_plural': 'Dars Jadvallari',
                'ordering': ['day_of_week', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('status', models.CharField(choices=[('B', 'Bor'), ('K', 'Kech qoldi'), ('Y', "Yo'q (Sababsiz)"), ('S', "Sababli yo'q")], default='B', max_length=1, verbose_name='Holat')),
                ('notified_telegram', models.BooleanField(default=False, verbose_name='Telegramga yuborildi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='apps.student', verbose_name="O'quvchi")),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='apps.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': "Yo'qlama",
                'verbose_name_plural': "Yo'qlamalar",
                'ordering': ['-date'],
                'unique_together': {('student', 'subject', 'date')},
            },
        ),
    ]
