# Generated by Django 6.0.7 on 2026-09-14 04:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="To'lov turi nomi")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Standart summa (UZS)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': "To'lov Turi",
                'verbose_name_plural': "To'lov Turlari",
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': "O'quvchi", 'verbose_name_plural': "O'quvchilar"},
        ),
        migrations.AddField(
            model_name='homework',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='homeworks/attachments/', verbose_name='Ilova fayl'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.teacher', verbose_name="O'qituvchi"),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='Yashash manzili'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Qabul qilingan sana'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Shoshilinch aloqa raqami'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], default='M', max_length=1, verbose_name='Jinsi'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Profil rasmi'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Faol'), ('INACTIVE', 'Nofaol'), ('GRADUATED', 'Bitirgan'), ('TRANSFERRED', "Ko'chirilgan")], db_index=True, default='ACTIVE', max_length=20, verbose_name='Holati'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name="O'quvchi ID kodi"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, verbose_name="Qisqacha ma'lumot"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, max_length=150, verbose_name="Ma'lumoti / Malaka toifasi"),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('B', 'Bor (Present)'), ('K', 'Kech qoldi (Late)'), ('Y', "Yo'q (Absent)"), ('S', "Sababli yo'q (Excused)")], db_index=True, default='B', max_length=1, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(db_index=True, verbose_name='Topshirish muddati'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name="O'quvchi telefoni"),
        ),
        migrations.AlterField(
            model_name='student',
            name='telegram_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba')], db_index=True, verbose_name='Hafta kuni'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name="E'lon matni")),
                ('target_role', models.CharField(choices=[('ALL', 'Barcha foydalanuvchilar'), ('TEACHERS', "Faqat o'qituvchilar"), ('STUDENTS', "Faqat o'quvchilar"), ('PARENTS', 'Faqat ota-onalar')], default='ALL', max_length=20, verbose_name="Mo'ljallangan auditoriya")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('grade_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.gradeclass', verbose_name='Muayyan sinf uchun')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Imtihon nomi')),
                ('exam_date', models.DateField(verbose_name="Imtihon o'tkazilish sanasi")),
                ('total_marks', models.IntegerField(default=100, verbose_name='Maksimal ball')),
                ('grade_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='apps.gradeclass', verbose_name='Sinf')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Imtihon',
                'verbose_name_plural': 'Imtihonlar',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('notification_type', models.CharField(choices=[('HOMEWORK', 'Uyga vazifa'), ('EXAM', 'Imtihon'), ('FEE', "To'lov eslatmasi"), ('ATTENDANCE', 'Davomat'), ('ANNOUNCEMENT', "E'lon")], default='ANNOUNCEMENT', max_length=20, verbose_name='Turi')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Havola')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xabarnoma',
                'verbose_name_plural': 'Xabarnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Kasbi / Ish joyi')),
                ('address', models.TextField(blank=True, verbose_name='Yashash manzili')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ota-ona (Vasiy)',
                'verbose_name_plural': 'Ota-onalar (Vasiylar)',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='apps.parentprofile', verbose_name='Ota-onasi / Vasiy'),
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Belgilangan summa (UZS)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Chegirma / Imtiyoz (UZS)')),
                ('due_date', models.DateField(db_index=True, verbose_name='Topshirish ohirgi muddati')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('PAID', "To'langan"), ('PARTIAL', "Qisman to'langan"), ('OVERDUE', "Muddati o'tgan")], db_index=True, default='PENDING', max_length=20, verbose_name='Holat')),
                ('academic_year', models.CharField(default='2026-2027', max_length=20, verbose_name="O'quv yili")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.feetype', verbose_name="To'lov turi")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='apps.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "O'quvchi To'lovi",
                'verbose_name_plural': "O'quvchilar To'lovlari",
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'langan summa (UZS)")),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name="To'lov sanasi")),
                ('payment_method', models.CharField(choices=[('CASH', 'Naqd pul'), ('CARD', 'Bank kartasi (Click/Payme)'), ('BANK', "Bank o'tkazmasi")], default='CARD', max_length=20, verbose_name="To'lov usuli")),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Tranzaksiya ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Kvitansiya / Chek raqami')),
                ('note', models.TextField(blank=True, verbose_name="Qo'shimcha izoh")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='apps.studentfee', verbose_name="To'lov hujjati")),
            ],
            options={
                'verbose_name': "To'lov Yozuvi",
                'verbose_name_plural': "To'lov Yozuvlari",
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Administrator'), ('TEACHER', "O'qituvchi"), ('ACCOUNTANT', 'Hisobchi (Accountant)'), ('RECEPTIONIST', 'Qabulxona (Receptionist)'), ('STUDENT', "O'quvchi"), ('PARENT', 'Ota-ona (Parent)')], db_index=True, default='STUDENT', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi Profili',
                'verbose_name_plural': 'Foydalanuvchi Profilari',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="To'plangan ball")),
                ('percentage', models.FloatField(verbose_name='Foiz (%)')),
                ('grade', models.CharField(max_length=5, verbose_name='Baho / Daraja (5,4,3,2 yoki A,B,C)')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name="Sinfdagi o'rni")),
                ('teacher_comments', models.CharField(blank=True, max_length=255, verbose_name="O'qituvchi izohi")),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='apps.exam', verbose_name='Imtihon')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='apps.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Imtihon Natijasi',
                'verbose_name_plural': 'Imtihon Natijalari',
                'ordering': ['-percentage'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True, verbose_name='Javob matni')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homeworks/submissions/', verbose_name='Bajarilgan vazifa fayli')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Topshirilgan vaqt')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('SUBMITTED', 'Topshirildi'), ('GRADED', 'Baholandi'), ('LATE', 'Kechikkan')], default='SUBMITTED', max_length=20, verbose_name='Holati')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Baho (1-100)')),
                ('teacher_feedback', models.TextField(blank=True, verbose_name="O'qituvchi fikri")),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='apps.homework', verbose_name='Uyga vazifa')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='apps.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "Vazifa Topshirig'i",
                'verbose_name_plural': 'Vazifa Topshiriqlari',
                'unique_together': {('homework', 'student')},
            },
        ),
    ]
