# Generated by Django 6.0.7 on 2026-07-29 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('status', models.CharField(choices=[('B', 'Bor'), ('K', 'Kech qoldi'), ('Y', "Yo'q")], default='B', max_length=1, verbose_name='Holat')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='apps.lesson', verbose_name='Dars')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='apps.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': "Yo'qlama",
                'verbose_name_plural': "Yo'qlamalar",
                'unique_together': {('student', 'lesson', 'date')},
            },
        ),
    ]
