# Generated by Django 6.0.7 on 2026-09-19 05:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_feetype_alter_student_options_homework_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='apps.teacher', verbose_name="O'qituvchi"),
        ),
        migrations.AddField(
            model_name='grade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='apps.gradeclass', verbose_name='Biriktirilgan sinflar'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_subjects',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='apps.subject', verbose_name='Biriktirilgan fanlar'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_role',
            field=models.CharField(choices=[('ALL', 'Barcha foydalanuvchilar'), ('TEACHERS', "Faqat o'qituvchilar"), ('STUDENTS', "Faqat o'quvchilar")], default='ALL', max_length=20, verbose_name="Mo'ljallangan auditoriya"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_teachers', to='apps.subject', verbose_name='Bosh fani'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('TEACHER', "O'qituvchi"), ('STUDENT', "O'quvchi")], db_index=True, default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Dars sarlavhasi')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name="Dars o'tilish sanasi")),
                ('description', models.TextField(blank=True, verbose_name='Dars mavzusi / tavsifi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='apps.gradeclass', verbose_name='Sinf')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='apps.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='apps.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='apps.lesson', verbose_name='Dars'),
        ),
    ]
