# Generated by Django 6.0.7 on 2026-09-20 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_grade_teacher_grade_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Baho (1-100)'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
