# Generated by Django 6.0.7 on 2026-09-30 11:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_grade_score_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Standart summa (UZS)'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="To'langan summa (UZS)"),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Belgilangan summa (UZS)'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Chegirma / Imtiyoz (UZS)'),
        ),
    ]
